# 중성화 X: Intact, O: Spayed , Neutered

SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.ANIMAL_TYPE, ANIMAL_OUTS.NAME
FROM (
    SELECT * FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE 'Intact%'
) INTACT_ANIMAL
INNER JOIN ANIMAL_OUTS
ON INTACT_ANIMAL.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE SEX_UPON_OUTCOME REGEXP('Spayed|Neutered')