-- 총매출 = 가격 * 주문량

WITH MAY_ORDER AS (
    SELECT PRODUCT_ID, AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE <'2022-06-01'
)
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P 
INNER JOIN MAY_ORDER AS O
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;