

SELECT J.FLAVOR AS FLAVOR
FROM FIRST_HALF AS H
INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS J_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) AS J
    ON H.FLAVOR = J.FLAVOR
    ORDER BY (TOTAL_ORDER + J_TOTAL_ORDER) DESC
    LIMIT 3
