-- 코드를 입력하세요 
# SELECT *
# FROM FIRST_HALF AS H
# INNER JOIN JULY AS J
# ON H.FLAVOR = J.FLAVOR

SELECT FLAVOR 
FROM (
    SELECT J.FLAVOR AS FLAVOR, TOTAL_ORDER + J_TOTAL_ORDER AS SUM
    FROM FIRST_HALF AS H
    INNER JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS J_TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR) AS J
        ON H.FLAVOR = J.FLAVOR
        ORDER BY SUM DESC
        LIMIT 3
)  AS RESULT
