SELECT HR_EMPLOYEES.DEPT_ID, DEPT_NAME_EN ,ROUND(SUM(SAL) / COUNT(EMP_NO)) AS AVG_SAL
FROM HR_EMPLOYEES
INNER JOIN HR_DEPARTMENT
ON HR_DEPARTMENT.DEPT_ID = HR_EMPLOYEES.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC;